export const socketConstants = {
    ONLINE: 'connect',
    DISCONNECT: 'disconnect',
    ERROR: 'error',
    CONNECT_ERROR: 'connect_error',
    NEW_MESSAGE_RECEIVED: 'newMessageReceived',
    MESSAGE_READ: 'messagesRead',
    ACCEPT_FRIEND_REQUEST: 'acceptFriendRequest',
    NEW_MEMBER_JOINED: 'newMembersJoined',
    NEW_GROUP_CHAT_CREATED: 'newGroupChatCreated',
    GROUP_CHAT_REMOVED: 'groupChatRemoved',
    GROUP_MEMBERS_REMOVED: 'groupMembersRemoved',
    UNSEND_MESSAGE_RECEIVED: 'unsendMessageReceived',
    SOMEONE_ONLINE: 'someoneOnline',
    SOMEONE_OFFLINE: 'someoneOffline',
    IS_ONLINE: 'isOnline',
    MESSAGE_DELETED: 'messageDeleted',
    MESSAGE_PINNED: 'messagePinned',
    MESSAGE_UNPINNED: 'messageUnpinned',
    CHAT_ERROR: 'chatError',
};
